language: java

# we need java 8
jdk:
- oraclejdk8

# skip build without tests
install: true
script: cd app && mvn install

# say 'go to hell' when there is a pb
notifications:
email:
  recipients:
    - christophe.maldivi@orange.com
    - denis.boisset@orange.com
    - manuel1.sanchez@orange.com
    - gilles.zanolin@orange.com
 on_success: change
 on_failure: always
